name: Schedule API Call

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 minutes

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
      - name: Log Current Time
        run: date -u  # Log the current UTC time
      - name: Make POST request to API
        run: |
          curl -X POST https://koinx-flame.vercel.app/api/crypto \
          -H "Content-Type: application/json"
